"use client";
import { useEffect } from "react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProviders from "@/components/session-provider";
import Providers from "@/components/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    // @ts-ignore
    import("preline");
  }, []);
  return (
    <html lang="en">
      <body
        className={`${inter.className}  bg-slate-200
       dark:bg-gray-800 overflow-x-hidden`}
      >
        <SessionProviders>
          <Providers> {children}</Providers>
        </SessionProviders>
      </body>
    </html>
  );
}
